# Generated by Django 4.1 on 2022-08-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='predicts',
            field=models.ManyToManyField(blank=True, to='ihlp.predict'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='slots',
            field=models.ManyToManyField(blank=True, to='ihlp.slot'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='machines',
            field=models.ManyToManyField(blank=True, to='ihlp.machine'),
        ),
    ]
