# Generated by Django 4.1.5 on 2023-01-22 13:52

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ihlp', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
