# Generated by Django 4.1.5 on 2023-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihlp', '0006_workloadtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workloadtotal',
            name='request_id',
        ),
        migrations.AlterField(
            model_name='workloadtotal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
