# Generated by Django 4.1.7 on 2023-03-25 21:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ihlp', '0007_remove_workloadtotal_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='WorkloadTotal',
        ),
        migrations.DeleteModel(
            name='RelationExportTasktype',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='username',
        ),
        migrations.AlterField(
            model_name='workload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
