# Generated by Django 4.1.7 on 2023-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihlp', '0008_responsible_delete_workloadtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='true_placement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='responsible',
            name='true_responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
