# Generated by Django 4.1.7 on 2023-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihlp', '0009_responsible_true_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='true_timeconsumption',
            field=models.IntegerField(default=True),
        ),
    ]
