# Generated by Django 4.1.7 on 2023-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihlp', '0010_responsible_true_timeconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='true_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
