# Generated by Django 4.1.7 on 2023-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihlp', '0011_responsible_true_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.IntegerField()),
                ('hide', models.IntegerField()),
            ],
        ),
    ]
