-- ihlp.request definition

CREATE TABLE `request` (
  `id` bigint(20) unsigned DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `itilState` varchar(100) DEFAULT NULL,
  `receivedDate` datetime DEFAULT NULL,
  `receivedVia` varchar(100) DEFAULT NULL,
  `serviceDisorderDate` datetime DEFAULT NULL,
  `automaticallyCreated` varchar(100) DEFAULT NULL,
  `callBackMethod` varchar(100) DEFAULT NULL,
  `cost` varchar(100) DEFAULT NULL,
  `timeConsumption` varchar(100) DEFAULT NULL,
  `numberOfAlarms` varchar(100) DEFAULT NULL,
  `subject` longtext DEFAULT NULL,
  `classification` varchar(100) DEFAULT NULL,
  `priority` varchar(100) DEFAULT NULL,
  `impact` varchar(100) DEFAULT NULL,
  `urgency` varchar(100) DEFAULT NULL,
  `deadline` datetime DEFAULT NULL,
  `investigationAndDiagnosis` varchar(100) DEFAULT NULL,
  `cause` varchar(100) DEFAULT NULL,
  `workAround` varchar(100) DEFAULT NULL,
  `solution` longtext DEFAULT NULL,
  `solutionDate` datetime DEFAULT NULL,
  `closingCode` varchar(100) DEFAULT NULL,
  `expectedSolutionDateTime` datetime DEFAULT NULL,
  `impactIfImplemented` varchar(100) DEFAULT NULL,
  `impactIfNotImplemented` varchar(100) DEFAULT NULL,
  `expectedResourceCost` varchar(100) DEFAULT NULL,
  `approvalOfContentOfTheRFC` varchar(100) DEFAULT NULL,
  `starttime` datetime DEFAULT NULL,
  `endtime` datetime DEFAULT NULL,
  `currentSection` varchar(100) DEFAULT NULL,
  `previousSections` varchar(100) DEFAULT NULL,
  `permanentlycloseddate` datetime DEFAULT NULL,
  UNIQUE KEY `request_id_IDX` (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;